name: Validate snippets
on:
  push:
    branches: [ main ]   # troque se sua branch padrão não for 'main'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run validator
        run: |
          python tools/validate_index.py --root . --index snippets/index.json
